INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:39] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:39] "[37mGET /students/Bob HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:43] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:43] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:44] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:50] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:50] "[37mGET /supervisor/Cheng2 HTTP/1.1[0m" 200 -
ERROR:app:Exception on /add-project [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 299, in add_project
    return render_template("supervisor/add-project.html");
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\templates\supervisor\add-project.html", line 3, in top-level template code
    {% extends "student/details/templates/page.html" %}
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\templates\student\details\templates\page.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\templates\base.html", line 3, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\templates\student\details\templates\page.html", line 36, in block "content"
    <form action="{{ url_for('student_details', username = current_user.name) }}/page{{num - 1}}">
jinja2.exceptions.UndefinedError: 'num' is undefined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:51] "[35m[1mGET /add-project HTTP/1.1[0m" 500 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 14:02:52] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
